export const API_LIST_REQUEST = "API_LIST_REQUEST";
export const API_LIST_SUCCESS = "API_LIST_SUCCESS";
export const API_LIST_FAIL = "API_LIST_FAIL";
export const API_LIST_RESET = "API_LIST_RESET";

export const API_CREATE_REQUEST = "API_CREATE_REQUEST";
export const API_CREATE_SUCCESS = "API_CREATE_SUCCESS";
export const API_CREATE_FAIL = "API_CREATE_FAIL";
export const API_CREATE_RESET = "API_CREATE_RESET";

export const API_DELETE_REQUEST = "API_DELETE_REQUEST";
export const API_DELETE_SUCCESS = "API_DELETE_SUCCESS";
export const API_DELETE_FAIL = "API_DELETE_FAIL";
export const API_DELETE_RESET = "API_DELETE_RESET";