export const CATEGORY_DRUG_LIST_REQUEST = "CATEGORY_DRUG_LIST_REQUEST";
export const CATEGORY_DRUG_LIST_SUCCESS = "CATEGORY_DRUG_LIST_SUCCESS";
export const CATEGORY_DRUG_LIST_FAIL = "CATEGORY_DRUG_LIST_FAIL";
export const CATEGORY_DRUG_LIST_RESET = "CATEGORY_DRUG_LIST_RESET";

export const CATEGORY_DRUG_SINGLE_REQUEST = "CATEGORY_DRUG_SINGLE_REQUEST";
export const CATEGORY_DRUG_SINGLE_SUCCESS = "CATEGORY_DRUG_SINGLE_SUCCESS";
export const CATEGORY_DRUG_SINGLE_FAIL = "CATEGORY_DRUG_SINGLE_FAIL";
export const CATEGORY_DRUG_SINGLE_RESET = "CATEGORY_DRUG_SINGLE_RESET";

export const CATEGORY_DRUG_DELETE_REQUEST = "CATEGORY_DRUG_DELETE_REQUEST";
export const CATEGORY_DRUG_DELETE_SUCCESS = "CATEGORY_DRUG_DELETE_SUCCESS";
export const CATEGORY_DRUG_DELETE_FAIL = "CATEGORY_DRUG_DELETE_FAIL";
export const CATEGORY_DRUG_DELETE_RESET = "CATEGORY_DRUG_DELETE_RESET";

export const CATEGORY_DRUG_CREATE_REQUEST = "CATEGORY_DRUG_CREATE_REQUEST";
export const CATEGORY_DRUG_CREATE_SUCCESS = "CATEGORY_DRUG_CREATE_SUCCESS";
export const CATEGORY_DRUG_CREATE_FAIL = "CATEGORY_DRUG_CREATE_FAIL";
export const CATEGORY_DRUG_CREATE_RESET = "CATEGORY_DRUG_CREATE_RESET";

export const CATEGORY_DRUG_UPDATE_REQUEST = "CATEGORY_DRUG_UPDATE_REQUEST";
export const CATEGORY_DRUG_UPDATE_SUCCESS = "CATEGORY_DRUG_UPDATE_SUCCESS";
export const CATEGORY_DRUG_UPDATE_FAIL = "CATEGORY_DRUG_UPDATE_FAIL";
export const CATEGORY_DRUG_UPDATE_RESET = "CATEGORY_DRUG_UPDATE_RESET";
