export const CONTENT_SINGLE_REQUEST = "CONTENT_SINGLE_REQUEST";
export const CONTENT_SINGLE_SUCCESS = "CONTENT_SINGLE_SUCCESS";
export const CONTENT_SINGLE_FAIL = "CONTENT_SINGLE_FAIL";
export const CONTENT_SINGLE_RESET = "CONTENT_SINGLE_RESET";

export const CONTENT_UPDATE_REQUEST = "CONTENT_UPDATE_REQUEST";
export const CONTENT_UPDATE_SUCCESS = "CONTENT_UPDATE_SUCCESS";
export const CONTENT_UPDATE_FAIL = "CONTENT_UPDATE_FAIL";
export const CONTENT_UPDATE_RESET = "CONTENT_UPDATE_RESET";