export const DRUGSTORE_LIST_REQUEST="DRUGSTORE_LIST_REQUEST";
export const DRUGSTORE_LIST_SUCCESS="DRUGSTORE_LIST_SUCCESS";
export const DRUGSTORE_LIST_FAIL="DRUGSTORE_LIST_FAIL";
export const DRUGSTORE_LIST_RESET="DRUGSTORE_LIST_RESET";

export const DRUGSTORE_ALL_REQUEST="DRUGSTORE_ALL_REQUEST";
export const DRUGSTORE_ALL_SUCCESS="DRUGSTORE_ALL_SUCCESS";
export const DRUGSTORE_ALL_FAIL="DRUGSTORE_ALL_FAIL";
export const DRUGSTORE_ALL_RESET="DRUGSTORE_ALL_RESET";

export const DRUGSTORE_SINGLE_REQUEST="DRUGSTORE_SINGLE_REQUEST";
export const DRUGSTORE_SINGLE_SUCCESS="DRUGSTORE_SINGLE_SUCCESS";
export const DRUGSTORE_SINGLE_FAIL="DRUGSTORE_SINGLE_FAIL";
export const DRUGSTORE_SINGLE_RESET="DRUGSTORE_SINGLE_RESET";

export const DRUGSTORE_CATEGORY_REQUEST="DRUGSTORE_CATEGORY_REQUEST";
export const DRUGSTORE_CATEGORY_SUCCESS="DRUGSTORE_CATEGORY_SUCCESS";
export const DRUGSTORE_CATEGORY_FAIL="DRUGSTORE_CATEGORY_FAIL";
export const DRUGSTORE_CATEGORY_RESET="DRUGSTORE_CATEGORY_RESET";

export const DRUGSTORE_CATEGORY_DRUG_REQUEST="DRUGSTORE_CATEGORY_DRUG_REQUEST";
export const DRUGSTORE_CATEGORY_DRUG_SUCCESS="DRUGSTORE_CATEGORY_DRUG_SUCCESS";
export const DRUGSTORE_CATEGORY_DRUG_FAIL="DRUGSTORE_CATEGORY_DRUG_FAIL";
export const DRUGSTORE_CATEGORY_DRUG_RESET="DRUGSTORE_CATEGORY_DRUG_RESET";

export const DRUGSTORE_DELETE_REQUEST="DRUGSTORE_DELETE_REQUEST";
export const DRUGSTORE_DELETE_SUCCESS="DRUGSTORE_DELETE_SUCCESS";
export const DRUGSTORE_DELETE_FAIL="DRUGSTORE_DELETE_FAIL";
export const DRUGSTORE_DELETE_RESET="DRUGSTORE_DELETE_RESET";

export const DRUGSTORE_CREATE_REQUEST="DRUGSTORE_CREATE_REQUEST";
export const DRUGSTORE_CREATE_SUCCESS="DRUGSTORE_CREATE_SUCCESS";
export const DRUGSTORE_CREATE_FAIL="DRUGSTORE_CREATE_FAIL";
export const DRUGSTORE_CREATE_RESET="DRUGSTORE_CREATE_RESET";

export const DRUGSTORE_UPDATE_REQUEST="DRUGSTORE_UPDATE_REQUEST";
export const DRUGSTORE_UPDATE_SUCCESS="DRUGSTORE_UPDATE_SUCCESS";
export const DRUGSTORE_UPDATE_FAIL="DRUGSTORE_UPDATE_FAIL";
export const DRUGSTORE_UPDATE_RESET="DRUGSTORE_UPDATE_RESET";

export const DRUGSTORE_IMPORT_REQUEST="DRUGSTORE_IMPORT_REQUEST";
export const DRUGSTORE_IMPORT_SUCCESS="DRUGSTORE_IMPORT_SUCCESS";
export const DRUGSTORE_IMPORT_FAIL="DRUGSTORE_IMPORT_FAIL";
export const DRUGSTORE_IMPORT_RESET="DRUGSTORE_IMPORT_RESET";