export const EXPORT_STOCK_LIST_REQUEST = "EXPORT_STOCK_LIST_REQUEST";
export const EXPORT_STOCK_LIST_SUCCESS = "EXPORT_STOCK_LIST_SUCCESS";
export const EXPORT_STOCK_LIST_FAIL = "EXPORT_STOCK_LIST_FAIL";
export const EXPORT_STOCK_LIST_RESET = "EXPORT_STOCK_LIST_RESET";

export const EXPORT_STOCK_DETAILS_REQUEST = "EXPORT_STOCK_DETAILS_REQUEST";
export const EXPORT_STOCK_DETAILS_SUCCESS = "EXPORT_STOCK_DETAILS_SUCCESS";
export const EXPORT_STOCK_DETAILS_FAIL = "EXPORT_STOCK_DETAILS_FAIL";
export const EXPORT_STOCK_DETAILS_RESET = "EXPORT_STOCK_DETAILS_RESET";

export const EXPORT_STOCK_DELETE_REQUEST = "EXPORT_STOCK_DELETE_REQUEST";
export const EXPORT_STOCK_DELETE_SUCCESS = "EXPORT_STOCK_DELETE_SUCCESS";
export const EXPORT_STOCK_DELETE_FAIL = "EXPORT_STOCK_DELETE_FAIL";
export const EXPORT_STOCK_DELETE_RESET = "EXPORT_STOCK_DELETE_RESET";

export const EXPORT_STOCK_CREATE_REQUEST = "EXPORT_STOCK_CREATE_REQUEST";
export const EXPORT_STOCK_CREATE_SUCCESS = "EXPORT_STOCK_CREATE_SUCCESS";
export const EXPORT_STOCK_CREATE_FAIL = "EXPORT_STOCK_CREATE_FAIL";
export const EXPORT_STOCK_CREATE_RESET = "EXPORT_STOCK_CREATE_RESET";

export const EXPORT_STOCK_STATUS_REQUEST = "EXPORT_STOCK_STATUS_REQUEST";
export const EXPORT_STOCK_STATUS_SUCCESS = "EXPORT_STOCK_STATUS_SUCCESS";
export const EXPORT_STOCK_STATUS_FAIL = "EXPORT_STOCK_STATUS_FAIL";
export const EXPORT_STOCK_STATUS_RESET = "EXPORT_STOCK_STATUS_RESET";

export const EXPORT_STOCK_UPDATE_REQUEST = "EXPORT_STOCK_UPDATE_REQUEST";
export const EXPORT_STOCK_UPDATE_SUCCESS = "EXPORT_STOCK_UPDATE_SUCCESS";
export const EXPORT_STOCK_UPDATE_FAIL = "EXPORT_STOCK_UPDATE_FAIL";
export const EXPORT_STOCK_UPDATE_RESET = "EXPORT_STOCK_UPDATE_RESET";

export const EXPORT_STOCK_CANCEL_REQUEST = "EXPORT_STOCK_CANCEL_REQUEST";
export const EXPORT_STOCK_CANCEL_SUCCESS = "EXPORT_STOCK_CANCEL_SUCCESS";
export const EXPORT_STOCK_CANCEL_FAIL = "EXPORT_STOCK_CANCEL_FAIL";
export const EXPORT_STOCK_CANCEL_RESET = "EXPORT_STOCK_CANCEL_RESET";