export const INVENTORY_CHECK_LIST_REQUEST = "INVENTORY_CHECK_LIST_REQUEST";
export const INVENTORY_CHECK_LIST_SUCCESS = "INVENTORY_CHECK_LIST_SUCCESS";
export const INVENTORY_CHECK_LIST_FAIL = "INVENTORY_CHECK_LIST_FAIL";
export const INVENTORY_CHECK_LIST_RESET = "INVENTORY_CHECK_LIST_RESET";

export const INVENTORY_CHECK_LIST_ITEM_REQUEST = "INVENTORY_CHECK_LIST_ITEM_REQUEST";
export const INVENTORY_CHECK_LIST_ITEM_SUCCESS = "INVENTORY_CHECK_LIST_ITEM_SUCCESS";
export const INVENTORY_CHECK_LIST_ITEM_FAIL = "INVENTORY_CHECK_LIST_ITEM_FAIL";
export const INVENTORY_CHECK_LIST_ITEM_RESET = "INVENTORY_CHECK_LIST_ITEM_RESET";

export const INVENTORY_CHECK_DETAILS_REQUEST = "INVENTORY_CHECK_DETAILS_REQUEST";
export const INVENTORY_CHECK_DETAILS_SUCCESS = "INVENTORY_CHECK_DETAILS_SUCCESS";
export const INVENTORY_CHECK_DETAILS_FAIL = "INVENTORY_CHECK_DETAILS_FAIL";
export const INVENTORY_CHECK_DETAILS_RESET = "INVENTORY_CHECK_DETAILS_RESET";

export const INVENTORY_CHECK_DELETE_REQUEST = "INVENTORY_CHECK_DELETE_REQUEST";
export const INVENTORY_CHECK_DELETE_SUCCESS = "INVENTORY_CHECK_DELETE_SUCCESS";
export const INVENTORY_CHECK_DELETE_FAIL = "INVENTORY_CHECK_DELETE_FAIL";
export const INVENTORY_CHECK_DELETE_RESET = "INVENTORY_CHECK_DELETE_RESET";

export const INVENTORY_CHECK_CREATE_REQUEST = "INVENTORY_CHECK_CREATE_REQUEST";
export const INVENTORY_CHECK_CREATE_SUCCESS = "INVENTORY_CHECK_CREATE_SUCCESS";
export const INVENTORY_CHECK_CREATE_FAIL = "INVENTORY_CHECK_CREATE_FAIL";
export const INVENTORY_CHECK_CREATE_RESET = "INVENTORY_CHECK_CREATE_RESET";

export const INVENTORY_CHECK_STATUS_REQUEST = "INVENTORY_CHECK_STATUS_REQUEST";
export const INVENTORY_CHECK_STATUS_SUCCESS = "INVENTORY_CHECK_STATUS_SUCCESS";
export const INVENTORY_CHECK_STATUS_FAIL = "INVENTORY_CHECK_STATUS_FAIL";
export const INVENTORY_CHECK_STATUS_RESET = "INVENTORY_CHECK_STATUS_RESET";

export const INVENTORY_CHECK_UPDATE_REQUEST = "INVENTORY_CHECK_UPDATE_REQUEST";
export const INVENTORY_CHECK_UPDATE_SUCCESS = "INVENTORY_CHECK_UPDATE_SUCCESS";
export const INVENTORY_CHECK_UPDATE_FAIL = "INVENTORY_CHECK_UPDATE_FAIL";
export const INVENTORY_CHECK_UPDATE_RESET = "INVENTORY_CHECK_UPDATE_RESET";

export const INVENTORY_CHECK_CANCEL_REQUEST = "INVENTORY_CHECK_CANCEL_REQUEST";
export const INVENTORY_CHECK_CANCEL_SUCCESS = "INVENTORY_CHECK_CANCEL_SUCCESS";
export const INVENTORY_CHECK_CANCEL_FAIL = "INVENTORY_CHECK_CANCEL_FAIL";
export const INVENTORY_CHECK_CANCEL_RESET = "INVENTORY_CHECK_CANCEL_RESET";
