export const INVENTORY_LIST_REQUEST = "INVENTORY_LIST_REQUEST";
export const INVENTORY_LIST_SUCCESS = "INVENTORY_LIST_SUCCESS";
export const INVENTORY_LIST_FAIL = "INVENTORY_LIST_FAIL";
export const INVENTORY_LIST_RESET = "INVENTORY_LIST_RESET";

export const INVENTORY_TO_CHECK_LIST_REQUEST = "INVENTORY_TO_CHECK_LIST_REQUEST";
export const INVENTORY_TO_CHECK_LIST_SUCCESS = "INVENTORY_TO_CHECK_LIST_SUCCESS";
export const INVENTORY_TO_CHECK_LIST_FAIL = "INVENTORY_TO_CHECK_LIST_FAIL";
export const INVENTORY_TO_CHECK_LIST_RESET = "INVENTORY_TO_CHECK_LIST_RESET";

export const INVENTORY_TAG_REQUEST = "INVENTORY_TAG_REQUEST";
export const INVENTORY_TAG_SUCCESS = "INVENTORY_TAG_SUCCESS";
export const INVENTORY_TAG_FAIL = "INVENTORY_TAG_FAIL";
export const INVENTORY_TAG_RESET = "INVENTORY_TAG_RESET";