export const MANUFACTURER_LIST_REQUEST = "MANUFACTURER_LIST_REQUEST";
export const MANUFACTURER_LIST_SUCCESS = "MANUFACTURER_LIST_SUCCESS";
export const MANUFACTURER_LIST_FAIL = "MANUFACTURER_LIST_FAIL";
export const MANUFACTURER_LIST_RESET = "MANUFACTURER_LIST_RESET";

export const MANUFACTURER_CREATE_REQUEST = "MANUFACTURER_CREATE_REQUEST";
export const MANUFACTURER_CREATE_SUCCESS = "MANUFACTURER_CREATE_SUCCESS";
export const MANUFACTURER_CREATE_FAIL = "MANUFACTURER_CREATE_FAIL";
export const MANUFACTURER_CREATE_RESET = "MANUFACTURER_CREATE_RESET";

export const MANUFACTURER_DELETE_REQUEST = "MANUFACTURER_DELETE_REQUEST";
export const MANUFACTURER_DELETE_SUCCESS = "MANUFACTURER_DELETE_SUCCESS";
export const MANUFACTURER_DELETE_FAIL = "MANUFACTURER_DELETE_FAIL";
export const MANUFACTURER_DELETE_RESET = "MANUFACTURER_DELETE_RESET";