export const PAGE_LIST_REQUEST = "PAGE_LIST_REQUEST";
export const PAGE_LIST_SUCCESS = "PAGE_LIST_SUCCESS";
export const PAGE_LIST_FAIL = "PAGE_LIST_FAIL";
export const PAGE_LIST_RESET = "PAGE_LIST_RESET";

export const PAGE_CREATE_REQUEST = "PAGE_CREATE_REQUEST";
export const PAGE_CREATE_SUCCESS = "PAGE_CREATE_SUCCESS";
export const PAGE_CREATE_FAIL = "PAGE_CREATE_FAIL";
export const PAGE_CREATE_RESET = "PAGE_CREATE_RESET";

export const PAGE_DELETE_REQUEST = "PAGE_DELETE_REQUEST";
export const PAGE_DELETE_SUCCESS = "PAGE_DELETE_SUCCESS";
export const PAGE_DELETE_FAIL = "PAGE_DELETE_FAIL";
export const PAGE_DELETE_RESET = "PAGE_DELETE_RESET";