export const PROVIDER_LIST_REQUEST = "PROVIDER_LIST_REQUEST";
export const PROVIDER_LIST_SUCCESS = "PROVIDER_LIST_SUCCESS";
export const PROVIDER_LIST_FAIL = "PROVIDER_LIST_FAIL";
export const PROVIDER_LIST_RESET = "PROVIDER_LIST_RESET";

export const PROVIDER_SINGLE_REQUEST = "PROVIDER_SINGLE_REQUEST";
export const PROVIDER_SINGLE_SUCCESS = "PROVIDER_SINGLE_SUCCESS";
export const PROVIDER_SINGLE_FAIL = "PROVIDER_SINGLE_FAIL";
export const PROVIDER_SINGLE_RESET = "PROVIDER_SINGLE_RESET";

export const PROVIDER_DELETE_REQUEST = "PROVIDER_DELETE_REQUEST";
export const PROVIDER_DELETE_SUCCESS = "PROVIDER_DELETE_SUCCESS";
export const PROVIDER_DELETE_FAIL = "PROVIDER_DELETE_FAIL";
export const PROVIDER_DELETE_RESET = "PROVIDER_DELETE_RESET";

export const PROVIDER_CREATE_REQUEST = "PROVIDER_CREATE_REQUEST";
export const PROVIDER_CREATE_SUCCESS = "PROVIDER_CREATE_SUCCESS";
export const PROVIDER_CREATE_FAIL = "PROVIDER_CREATE_FAIL";
export const PROVIDER_CREATE_RESET = "PROVIDER_CREATE_RESET";

export const PROVIDER_UPDATE_REQUEST = "PROVIDER_UPDATE_REQUEST";
export const PROVIDER_UPDATE_SUCCESS = "PROVIDER_UPDATE_SUCCESS";
export const PROVIDER_UPDATE_FAIL = "PROVIDER_UPDATE_FAIL";
export const PROVIDER_UPDATE_RESET = "PROVIDER_UPDATE_RESET";
