export const REQ_INVENTORY_LIST_REQUEST = "REQ_INVENTORY_LIST_REQUEST";
export const REQ_INVENTORY_LIST_SUCCESS = "REQ_INVENTORY_LIST_SUCCESS";
export const REQ_INVENTORY_LIST_FAIL = "REQ_INVENTORY_LIST_FAIL";
export const REQ_INVENTORY_LIST_RESET = "REQ_INVENTORY_LIST_RESET";

export const REQ_INVENTORY_DETAILS_REQUEST = "REQ_INVENTORY_DETAILS_REQUEST";
export const REQ_INVENTORY_DETAILS_SUCCESS = "REQ_INVENTORY_DETAILS_SUCCESS";
export const REQ_INVENTORY_DETAILS_FAIL = "REQ_INVENTORY_DETAILS_FAIL";
export const REQ_INVENTORY_DETAILS_RESET = "REQ_INVENTORY_DETAILS_RESET";

export const REQ_INVENTORY_DELETE_REQUEST = "REQ_INVENTORY_DELETE_REQUEST";
export const REQ_INVENTORY_DELETE_SUCCESS = "REQ_INVENTORY_DELETE_SUCCESS";
export const REQ_INVENTORY_DELETE_FAIL = "REQ_INVENTORY_DELETE_FAIL";
export const REQ_INVENTORY_DELETE_RESET = "REQ_INVENTORY_DELETE_RESET";

export const REQ_INVENTORY_CREATE_REQUEST = "REQ_INVENTORY_CREATE_REQUEST";
export const REQ_INVENTORY_CREATE_SUCCESS = "REQ_INVENTORY_CREATE_SUCCESS";
export const REQ_INVENTORY_CREATE_FAIL = "REQ_INVENTORY_CREATE_FAIL";
export const REQ_INVENTORY_CREATE_RESET = "REQ_INVENTORY_CREATE_RESET";

export const REQ_INVENTORY_STATUS_REQUEST = "REQ_INVENTORY_STATUS_REQUEST";
export const REQ_INVENTORY_STATUS_SUCCESS = "REQ_INVENTORY_STATUS_SUCCESS";
export const REQ_INVENTORY_STATUS_FAIL = "REQ_INVENTORY_STATUS_FAIL";
export const REQ_INVENTORY_STATUS_RESET = "REQ_INVENTORY_STATUS_RESET";

export const REQ_INVENTORY_UPDATE_REQUEST = "REQ_INVENTORY_UPDATE_REQUEST";
export const REQ_INVENTORY_UPDATE_SUCCESS = "REQ_INVENTORY_UPDATE_SUCCESS";
export const REQ_INVENTORY_UPDATE_FAIL = "REQ_INVENTORY_UPDATE_FAIL";
export const REQ_INVENTORY_UPDATE_RESET = "REQ_INVENTORY_UPDATE_RESET";

export const REQ_INVENTORY_CANCEL_REQUEST = "REQ_INVENTORY_CANCEL_REQUEST";
export const REQ_INVENTORY_CANCEL_SUCCESS = "REQ_INVENTORY_CANCEL_SUCCESS";
export const REQ_INVENTORY_CANCEL_FAIL = "REQ_INVENTORY_CANCEL_FAIL";
export const REQ_INVENTORY_CANCEL_RESET = "REQ_INVENTORY_CANCEL_RESET";
