export const UNIT_LIST_REQUEST = "UNIT_LIST_REQUEST";
export const UNIT_LIST_SUCCESS = "UNIT_LIST_SUCCESS";
export const UNIT_LIST_FAIL = "UNIT_LIST_FAIL";
export const UNIT_LIST_RESET = "UNIT_LIST_RESET";

export const UNIT_CREATE_REQUEST = "UNIT_CREATE_REQUEST";
export const UNIT_CREATE_SUCCESS = "UNIT_CREATE_SUCCESS";
export const UNIT_CREATE_FAIL = "UNIT_CREATE_FAIL";
export const UNIT_CREATE_RESET = "UNIT_CREATE_RESET";

export const UNIT_DELETE_REQUEST = "UNIT_DELETE_REQUEST";
export const UNIT_DELETE_SUCCESS = "UNIT_DELETE_SUCCESS";
export const UNIT_DELETE_FAIL = "UNIT_DELETE_FAIL";
export const UNIT_DELETE_RESET = "UNIT_DELETE_RESET";